### ISSUE TITLE
Slow search in the menu

### ISSUE THREAD

**Issue by deevroman** [lxqt/lxqt-panel#1168]
After typing the next letter, the search interface hangs. The next letter can only be typed after a few seconds.

**Comment by agaida** [comment]
ok - you want it - you get it - no bug without filled out form.

!--- Provide a general summary of the issue in the title above. You       --->
!--- should not delete relevant sections and/or questions in your report  --->

!--- BEFORE FILLING OUT THIS REPORT FORM:                                 --->
!--- Dear users of stable and LTS (long term service) distributions:      --->
!--- Please do NOT file bugs against old (dead) versions but use your     --->
!--- distribution bugtracker instead. This is esp. true for Ubuntu LTS.   --->

**Comment by tsujan** [comment]
Yes, this was a bad report -- if it was a report at all -- but there's something valid in it. Although I don't see any delay (which the reporter mistakenly called "hang"), it's possible because Qt emits `QLineEdit::textChanged` too fast. I'll open 2 issues and make 2 PRs (for Panel and Runner) when I find the time (not soon).

**Comment by tsujan** [comment]
See https://github.com/lxqt/lxqt-panel/pull/1173

I didn't have time to open an issue; just the fix, with a simple way of reproducing the freeze-like behavior (i.e., keeping "A" pressed).
