### ISSUE TITLE
Inconsistent handling of mouse wheel events to switch tabs/desktops/windows

### ISSUE THREAD

**Issue by nacktmull** [lxqt/lxqt-panel#1193]
Qt's default handling of mouse wheel events to switch tabs in a tab widget works fine (on my desktops) out of the box.
Plugin-desktopswitch also works for me, but plugin-taskbar requires me to scroll the wheel (one that "clicks" after every move, no "clickless" wheel or however that's called) three times to switch to the next/previous desktop.
I had a look at the sources and noticed the different thresholds in desktopswitch and taskbar (100 vs. 300). I then saw there's a workaround in the master branch of plugin-taskbar that adds a "wheelDeltaThreshold" option to manually override the fixed 300 threshold from tag 0.14.1.
That's a great improvement and will probably solve the problem for me, although I would prefer a consistent handling, e.g. by adding a global threshold setting that's also respected by plugin-desktopswitch.
But I cannot remember that I ever had a need to configure such a threshold. Firefox, Qt, every application supporting tab switching per mouse wheel just seemed to work out of the box. Qt seems to use a different approach than LXQt. They evaluate QWheelEvent->angleDelta() in QTabBar, while plugin-desktopswitch and plugin-taskbar rely on QWheelEvent->delta(), which seems to be deprecated since Qt 5.0.
The code for tab switching in qtabbar.cpp is:

#if QT_CONFIG(wheelevent)
void QTabBar::wheelEvent(QWheelEvent *event)
{
#ifndef Q_OS_MAC
    Q_D(QTabBar);
    int delta = (qAbs(event->angleDelta().x()) > qAbs(event->angleDelta().y()) ?
                     event->angleDelta().x() : event->angleDelta().y());
    int offset = delta > 0 ? -1 : 1;
    d->setCurrentNextEnabledIndex(offset);
    QWidget::wheelEvent(event);
#else
    Q_UNUSED(event)
#endif
}
#endif // QT_CONFIG(wheelevent)

It seems there's no threshold required at all.
Would it be possible to use the same code in LXQt to get consistent mouse wheel switching in Qt and LXQt, no matter if switching tabs, desktops, active windows or whatever?

PS: Switching tabs per mouse wheel was the reason why I migrated from Xfce to LXQt. GTK3 killed that feature. Please please please, never consider disabling this in LXQt. Make it optional for people with stupid mice or who accidentally happen to hit the scroll wheel (I don't know how that can happen, but it seems to be a problem for some). I LOVE switching tabs with the wheel, it's one of the most convenient features I've seen on Linux, and I sorely miss it on Windows and now Xfce.

**Comment by agaida** [comment]
Nice text - but you missed something important, we did the bug template for am important reason - please don't waste our time with incomplete bug reports! It might be hard for you to understand:

#### Not having processed the template leads to the following

* the bug report will be closed without any processing
* even if your report contains valuable informations - we can't trust them because you are unable to read and understand the template
* in case you are complaining about closing your bug without any comment: God damn - you are ignorant and waste our precious time - and you fucking know about it!  After having read the template you decided to ignore the formal prerequisites for filing a bug. 

@tsujan, @wxl, @tsimonq - some people will never learn - so please, for god sake, let us integrate these three points into the bug template. I'm more than pissed and i want to have it in.

**Comment by tsujan** [comment]
> some people will never learn

They may think we do nothing here and have lots of time to read -- although a glance at commits would show otherwise.

> for god sake, let us integrate these three points into the bug template.

IMHO, something this may be enough: "The report might be closed if the template is not used."

**Comment by palinek** [comment]
@nacktmull based on your post you seem to be oriented well and are familiar with C++/Qt... Would you mind to implement those changes and submit PR(s)?
