### ISSUE TITLE
Visual GUI bug Panel Volume Control

### ISSUE THREAD

**Issue by alexandre1985** [lxqt/lxqt-panel#1425]
System Information

* Distribution & Version: ArchLinux x64
* Kernel: 5.4.46-1-lts
* Qt Version: 5.15.0-3
* liblxqt Version: 0.15.1-1
* lxqt-build-tools Version: ?
* lxqt-panel Version: 0.15.1-1
* lxqt-qtplugin Version: 0.15.1-2

I have this video, that demonstrates the visual bug clearly.  
Please focus on the Volume Control inside the Desktop Panel.

[Video link](https://streamable.com/mgyrds)

**Comment by tsujan** [comment]
> I have this video, that demonstrates the visual bug clearly.

They say a picture is worth ten thousand words. This case shows that may not be true.

Please describe the problem clearly, by using words.

**Comment by alexandre1985** [comment]
The volume control of the desktop panel, is off-centered. Misaligned horizontally.
Only when I enter the desktop panel configuration, it automatically (and mystereously) aligns itself.
The off-centering happens everytime that I boot the ArchLinux OS.

**Comment by tsujan** [comment]
Thanks!

Since it's never misaligned here (I also use a vertical panel), I should first find the conditions under which it is. Will test with different panel widths later.

**Comment by alexandre1985** [comment]
:smiley: :+1:

**Comment by tsujan** [comment]
Sorry for the long delay! I succeeded in reproducing this issue by increasing the panel size and making it thicker. Apparently, it happens with plugins that consist of tool buttons — the volume button is one of them.

The code sets a correct size policy (expanding both horizontally and vertically) but, for some reason, the size policy isn't respected at first. Changing the volume or showing the config dialog "activates" the size policy. The problem may be deeper than meets the eye.

**Comment by tsujan** [comment]
OK, found the cause: It's about how Qt draws buttons.

At startup, the size of the tool button is set while it isn't shown to its parent yet and so, the style size is used (a rectangle). Afterward, when the plugin is updated by any means, the button is already shown to its parent (a `QFrame`) and its size policy is recognized.

Updating the panel or its plugins at startup doesn't solve the problem because the tool button isn't shown to its parent at that moment and `QWidget::update()` has no effect when the widget is hidden. But the fix is easy: update the button's geometry and adjust its size as soon as it's shown to its parent (by checking `QEvent::ShowToParent` inside the event-filter method of  `plugin.cpp`).

Will make a PR after some tests.

**Comment by alexandre1985** [comment]
I want to test this bug fixing. in which version of lxqt-panel is this fix implemented?

**Comment by tsujan** [comment]
> I want to test this bug fixing

It's already tested and merged.

> in which version of lxqt-panel is this fix implemented?

In latest git, for which you need git LXQt. But it'll be in 0.16 and I think it won't take long until 0.16 is released.

**Comment by alexandre1985** [comment]
Ok. Thanks

A 3 de setembro de 2020 11:51:48 WEST, tsujan <notifications@github.com> escreveu:
>> I want to test this bug fixing
>
>It's already tested and merged.
>
>> in which version of lxqt-panel is this fix implemented?
>
>In latest git, for which you need git LXQt. But it'll be in 0.16 and I
>think it won't take long until 0.16 is released.
