### ISSUE TITLE
panel 1.2 volume widget loose focus.

### ISSUE THREAD

**Issue by ringo32** [lxqt/lxqt-panel#1839]
Endeavouros / Archlinux based

when click on the widget of volume, using the keyboard widget loose focus. in panel 1.1 it worked

(thhis report is for someone else.)
##### Expected Behavior

when click on the widget  using the arrows the volume should not loose focus
##### Current Behavior

click on the widget when tab the key widget loose focus.

##### Possible Solution

i dontg know ...
##### Steps to Reproduce (for bugs)

1.
2.
3.
4.

##### Context
fairly to say it is a report for someone else., but it loose here also focus. but doesnt bother me.
he downgraded the panel to 1.1 and seems to work again.

##### System Information

* LXQt Version:
* Distribution & Version:
* Qt Version:
* liblxqt Version:
further archlinux based endeavouros..

local/qt5-base 5.15.7+kde+r176-1 (qt qt5)
    A cross-platform application and UI framework
[ringo@lxqt ~]$ pacman -Qs liblxqt
local/liblxqt 1.2.0-1
    Common base library for LXQt components
[ringo@lxqt ~]$ 

its from someone else but is a bug for him..

**Comment by stefonarch** [comment]
I can confirm that, in 1.2.0 the icon popup loses focus always after ~1 sec and it does it also when the arrows are used to move the slider - but not when using the mouse. In VM Lubuntu with 1.1.0 and in debian 1.1.0 behavior is ok.

**Comment by tsujan** [comment]
The only change was setting the window flags in the c-tor: https://github.com/lxqt/lxqt-panel/commit/3bfd7b9ea3a844d85a995f91451e88cd0eb602df

I'll check whether that's the cause. If it is, we'll have a new problem.

**Comment by stefonarch** [comment]
Right, but the brightness slider didn't loose focus.

**Comment by tsujan** [comment]
I tested an saw that exactly that commit changed the behavior.

> but the brightness slider didn't loose focus.

Right, because the other parts of the codes are different. I'll see if I could fix the problem while keeping https://github.com/lxqt/lxqt-panel/commit/3bfd7b9ea3a844d85a995f91451e88cd0eb602df. My guess is that we were just lucky before V1.2.0.

**Comment by tsujan** [comment]
OK, this is the problem:

With the above mentioned commit, when the user clicks the volume button, the popup makes Qt send a "leave event" to the button, and that event will close the popup after one second if the cursor isn't moved to the popup.

The problem is worse that what's reported: If you uncheck "Show on mouse click" in the config dialog and put the mouse cursor over the button, the popup appears and disappears indefinitely, and you'll have no way of right clicking it and change that setting again.

I think setting the flag triggers a Qt problem that we avoided by chance before (there was no comment in the code). Will try to find a solution.

**Comment by tsujan** [comment]
Sorry to add comment after comment, but this is important too:

A problem I mentioned above was already in lxqt-panel < 1.2.0 but in a milder form. With lxqt-panel < 1.2.0 and with "Show on mouse click" unchecked, if the user right clicked the button *while the popup was shown*, he should act quickly; otherwise the context menu would disappear after one second.

IMHO, if we don't want the code to based on luck, we should remove that option and make the volume button behave exactly like backlight button. The disappearance of the popup after the cursor is left can be kept intact, although it wouldn't be as useful as before. Reversing https://github.com/lxqt/lxqt-panel/commit/3bfd7b9ea3a844d85a995f91451e88cd0eb602df isn't a real solution.

@palinek, your comment would be appreciated.

**Comment by stefonarch** [comment]
I see, I did use never the slider with this option unchecked, it's annoying that it pops up when moving the mouse over the panel, so I agree with removing.

**Comment by tsujan** [comment]
Here I sum up my coding argument for more readability.

If a button has an active popup (like a menu), it shouldn't receive any enter or leave event while the popup is shown. The fact that it did before V1.2.0 was because of a "good" bug in Qt. https://github.com/lxqt/lxqt-panel/commit/3bfd7b9ea3a844d85a995f91451e88cd0eb602df avoided that bug, which had appeared under Wayland in another way.

Put simply, my argument is that relying on the button's enter and leave events with a *visible* popup is wrong — even if possible by chance. So,

 1. The option in question should have been removed before V1.2.0.
 2. The popup can't be made hidden by just moving the cursor outside the button; the user needs to press Escape or click somewhere (as with the backlight button).
 3. Hiding the popup when the cursor leaves it is still possible but not very useful.
