### ISSUE TITLE
Urgency hint is not cleared when using mouse wheel to switch between applications.

### ISSUE THREAD

**Issue by Chiitoo** [lxqt/lxqt-panel#1904]
##### Expected Behavior

Panel task manager widget "urgency hint" is cleared.

##### Current Behavior

After 44c46c163b7 [1], for some applications the urgency hint might not be cleared at all, or only very briefly, and for some it is cleared only when the application item is clicked on the panel.

After e601a6bf652 [2], it seems this might be partially fixed in that the hint seems to go away when I click the window of the application, but it does not go away when using the mouse wheel to scroll from an application to another over the panel (it has had some other problems for a long time that I've meant to report, in that it doesn't seem to switch between all applications, but only of the same type(?), like lximage-qt.  Previously this would clear the hints at least, even if it didn't actually raise a window...

Perhaps this is more about the mouse wheel switching than the urgency hint at this point, since so far the hint seems to behave correctly after a quick test.

1. https://github.com/lxqt/lxqt-panel/commit/44c46c163b7282fd521b3cf361e6f87c88a48a9f
2. https://github.com/lxqt/lxqt-panel/commit/e601a6bf652e8f4a2ca444344cf098306fe31285

##### Steps to Reproduce (for bugs)

1. Open several different applications.
2. Switch between the applications using the mouse wheel over the panel task manager widget.

##### Context

Thank you for working on this!

I had been noticing this oddness for a while now, and in recent days was starting to think that this is related to a different funny issue, but I had not looked at the latest commits to lxqt-panel yet.  : ]

Funny issue: https://bugs.kde.org/show_bug.cgi?id=469426

##### System Information

* LXQt Version: git master
* Distribution & Version: Gentoo Linux
* Qt Version: 5.15.10
* liblxqt Version: git master

**Comment by palinek** [comment]
Can the described behavior be seen only with kwin?
The urgency flag of taskbar button should be cleared upon notification from WM, it is not anyhow cleared based on the clicking/scrolling on the taskbar itself.

**Comment by tsujan** [comment]
> Can the described behavior be seen only with kwin?

Here, with KWin, I see no problem.

My guess is that @Chiitoo described the focus stealing prevention. Cycling though the task buttons by turning mouse wheel doesn't necessarily activate windows; it just "requests" activation. It's up to the WM and its degree of focus stealing prevention to activate the window or just show an urgency.

Now, the user may ask, "Why is wheel cycling is different from click cycling?" IMO, the current behavior is reasonable because the mouse wheel can turn quickly, and focus stealing prevention exists for a reason.

**Comment by tsujan** [comment]
Focus stealing aside, after I chose "Cycle windows on wheel scrolling" (not what I used before) and played with it, I encountered situations like this:

![buttons](https://github.com/lxqt/lxqt-panel/assets/981076/36c8d7bb-6883-4900-b82a-59ecb7821a43)

A mere wheel cycling shouldn't make multiple task buttons urgent (red in the screenshot).

This isn't a new problem; I checked 1.2.1 and saw it.

**Comment by Chiitoo** [comment]
Oh, yeah, it does seem Openbox does it a bit differently.

And yeah, that's in part what I was trying to describe, where multiple applications get the hint.  It was been there before, yeah, but after the latest changes, scrolling the wheel more would take the hint off as well, but not any longer.

**Comment by tsujan** [comment]
Either GitHub removed my last comment, or I forgot to press the Comment button.

Anyway, bypassing the focus stealing prevention seems to be the only way: https://github.com/lxqt/lxqt-panel/pull/1905

Users of Openbox didn't see the issue because Openbox doesn't have this property (by default?), and those like me who were familiar with focus stealing prevention didn't cycle windows with wheel (I use the wheel to move windows to other desktops). The issue is very old.

**Comment by Chiitoo** [comment]
Thanks!

That change does make things happen more like I had expected
