### ISSUE TITLE
Hitting "enter" closes "Add plugin" dialog

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-panel#1910]
Default button is "cancel" always.

##### Expected Behavior

Searching for a plugin and hitting enter with one plugin highlighted closes the dialog.
##### Current Behavior

It should add the selected plugin.
##### Steps to Reproduce (for bugs)

1. Right click on panel → add widget
2. Search for something, the first result is highlighted, or highlight another
3. Hit "enter"
4. Dialog closes, no widget added.

                                             
* LXQt Version: all

**Comment by isf63** [comment]
One _possible_ solution is to remove properties 'autoDefault' and 'default' from `<widget class="QPushButton" name="closeButton">` in `./panel/config/addplugindialog.ui`. This causes the "Add Widget" button to activate on Enter instead of Cancel.

![screenshot](https://github.com/lxqt/lxqt-panel/assets/121320947/657d3655-b7a1-41ba-9fa7-72b44bdaf3d3)
