### ISSUE TITLE
Fancy Menu: Icons for some applications not appearing immediately

### ISSUE THREAD

**Issue by isf63** [lxqt/lxqt-panel#2172]
##### Current Behavior
Icons for some applications do not consistently show immediately.

##### Steps to Reproduce (for bugs)
1. Install `mgba-qt` and `pcsx2`.
Note: The relevant icons are - `/usr/share/pixmaps/io.mgba.mGBA.png` and `/usr/share/pixmaps/PCSX2.png`.
3. Restart the panel.
4. In Fancy Menu open any category other than the "Games" category. (This step is not always needed)
5. Open the "Games" category.
For these two applications there will be no icons until going out of, then back into, the category. This fixes the bug until next panel restart.

##### Context
I opened https://github.com/lxqt/libqtxdg/issues/305 previously in part due to this issue. But the example there turned out to be unrelated.

##### System Information

* LXQt Version: git
* Qt Version: qt6-base 6.8.0, qt5-base 5.15.15+kde+r141
* liblxqt Version: git

**Comment by tsujan** [comment]
Usually, reports shouldn't require installations. Anyway, I installed `mgba-qt` from Arch. It had only one item under the Games category, whose icon was loaded with a one-second delay at first. That's not unexpected for a 256-px PNG icon inside `/usr/share/pixmaps/`, because there's no icon cache there and its the last place that's searched.

**Comment by tsujan** [comment]
I closed the report not because it wasn't valid (it was, and thanks for reporting!), but because there's nothing to do about it.

**Comment by isf63** [comment]
A few things:

- I can confirm that they are large icons: `/usr/share/pixmaps/io.mgba.mGBA.png` is 256x256; `/usr/share/pixmaps/PCSX2.png` is 512x512.

- It looks like this bug is only present when using auto-select in Fancy Menu. I can reproduce it every time by 1) Restarting the panel and making sure auto-select is enabled; 2) Navigate to a category other than "Games"; 3) Hover over the "Games" category.
The large, uncached icons will not be loaded (until mousing into the category's applications.)

**Comment by tsujan** [comment]
> It looks like this bug is only present when using auto-select in Fancy Menu.

I know that you're describing your observation, but auto-selection has nothing to do with icons.

> The large, uncached icons will not be loaded

In my case, the icon was loaded with a short delay, without me changing the category. The cause of delay may be three things, all of which are out of our control: lack of icon cache inside the pixmaps folder, the big icon size, or how `QListView` reacts to them. To rule out or confirm the third cause, please test with Main Menu too.

**Comment by isf63** [comment]
>or how QListView reacts to them. To rule out or confirm the third cause, please test with Main Menu too.

Main Menu seemingly works in this case with no problems at all.

**Comment by isf63** [comment]
Resizing them down to 48x48 still produces the bug. It must be due to `/usr/share/pixmaps/` then, specifically in Fancy Menu.

**Comment by tsujan** [comment]
> it must be due to /usr/share/pixmaps/ then

Hard to tell for sure, but yes, maybe. `QMenu` may do the needed computations before being shown, while `QListView` does it after being shown.

I remember a similar case in pcmanfm-qt. The icon of "Electron" was shown with a delay inside `/usr/share/applications/`. It was a huge icon (1024x1024) inside `/usr/share/pixmaps/`. The problem was fixed after I made a reasonable SVG icon for Electron, added it to my icon set, and updated its cache.
