### ISSUE TITLE
allow easy moving applications between monitors

### ISSUE THREAD

**Issue by bjlockie** [lxqt/lxqt-panel#965]
Add "Move to monitor" menu to taskbar that lets the user right click on a running application and move it to a monitor.
I have 2 monitors and it would be nice to easily move applications between monitors.

![image](https://user-images.githubusercontent.com/303873/52251735-acdb3f80-28cc-11e9-98a8-22772bb6f25e.png)

If VLC is full screen then the move option is disabled.
It'd be nice to move without first taking it out of full screen mode.

**Comment by TomaszPluta** [comment]
I also found it useful and I'm currently working on the solution (let's say, half done)

**Comment by TomaszPluta** [comment]
I just stuck with this. 
It is impossible to get handler for mWindow to use: 
`windowHandle()->setScreen(qApp->screens()[n]); `
Otherwise, I know, that it could be done by getting rectangle for screens
 QScreen* screen  = qApp->screens()[0];
 QRect screenRect = screen->geometry();
but I dont see any possibility to move window to recalculated position. Move like in "moveApplication" option:
`NETRootInfo(QX11Info::connection(), NET::WMMoveResize).moveResizeRequest(mWindow, X, Y, NET::Move);`
 leaves window on new position, but ready to by moved by cursor (mouse).

**Comment by bjlockie** [comment]
I don't know Qt programming.
I would ask on https://forum.qt.io/

**Comment by tsujan** [comment]
Closed in https://github.com/lxqt/lxqt-panel/commit/c69f8201d1d67894ad6ce72e4dd7cc5061ed2fa3
